<?php

/*
 * Custom code for GSLIS IMS app
 */
/*
 * ims_add_org_acl
 * add update permission to an organization for a particular user
 * @param string $uid
 * @param array $form_state
 * @param string $nid = organization node id
 * @return nothing
 */
function ims_add_org_acl($uid, &$form_state, $nid) {
  $debug = FALSE;
  
  if ($debug) watchdog('ims_add_org_acl', "Adding ACL to @node for @user - @username", array('@node' => $nid, '@user' => $uid, '@username' => $form_state['values']['name']));
  
  $node = node_load($nid);
  if (isset($node)) {
    if ($debug) watchdog('ims_add_org_acl', "Loaded nid: @nid - @node", array('@nid' => $nid, '@node' => $node->title));
    
    //get the current settings 
    $settings = content_access_get_per_node_settings($node);
    if (!isset($settings)) {
      //if this node has not been used before then we have to establish default settings
      $settings['view']        = array(2, 3);     
      $settings['view_own']    = array(2, 3);
      $settings['update']      = array(3);
      $settings['update_own']  = array(3);
      $settings['delete']      = array(3);
      $settings['delete_own']  = array(3);
      // Save per-node settings.
      content_access_save_per_node_settings($node, $settings);
    }
    
    // we only care about one operation, update
    $op = 'update';
    
    //returns an acl_id (if it doesn't exist, one is created)
    $acl_id = content_access_get_acl_id($node, $op);
    acl_node_add_acl($node->nid, $acl_id, (int) ($op == 'view'), (int) ($op == 'update'), (int) ($op == 'delete'), content_access_get_settings('priority', $node->type));
    
    if ($debug) watchdog('ims_add_org_acl', "Got acl_id: @acl_id for @node", array('@acl_id' => $acl_id, '@node' => $node->title));
    //store it
    $form_state['values']['acl'][$op]['acl_id'] = $acl_id;
    $form_state['values']['acl'][$op]['deletions'][$uid] = 0;
    $form_state['values']['acl'][$op]['delete_button'] = 'Remove Checked';
    $form_state['values']['acl'][$op]['add'] = '';
    $form_state['values']['acl'][$op]['add_button'] = 'Add User';
    
    //create a serialized user list for ims_acl_save
    $user_list[$uid] = $form_state['values']['name'];
    $form_state['values']['acl'][$op]['user_list'] = serialize($user_list);
    
    // following if statement is for robustness. The acl module MUST be enabled
    if (module_exists('acl')) {
      db_insert('acl_user')
       ->fields(array(
       'acl_id' => $acl_id,
       'uid' => $uid,
      ))
      ->execute();
      module_invoke_all('user_acl', $settings);
    }

    // from the content_access.module and content_access.admin.inc
    // Apply new settings.
    node_access_acquire_grants($node);

    module_invoke_all('per_node', $settings);
  }
}
function ims_evaluation_node_submit(&$form, &$form_state) {
  $student_profile = profile2_load($form_state['values']['field_eval_student']['und'][0]['target_id']);
  $form_state['values']['title'] .=  (string) $student_profile->field_stp_fname['und'][0]['value'] . ' ';
  $form_state['values']['title'] .=  (string) $student_profile->field_stp_lname['und'][0]['value'];

}
function ims_final_evaluation_node_submit(&$form, &$form_state) {
  $student_profile = profile2_load($form_state['values']['field_fin_student']['und'][0]['target_id']);
  $form_state['values']['title'] .=  (string) $student_profile->field_stp_fname['und'][0]['value'] . ' ';
  $form_state['values']['title'] .=  (string) $student_profile->field_stp_lname['und'][0]['value'];

}
/*
 * quick way to display formID; will be commented most of the time 
 
function ims_form_alter(&$form, &$form_state, $formID) {
  dpm($form);
  dpm($form_state);
}
*/
/**
* @file
* Build the drop-down list of students from the internship node
* Set the default supervisor name to the supervisor on the internship
* 
*/
/* Implements hook_form_FORM_ID_alter(). */
 function ims_form_evaluation_node_form_alter(&$form, &$form_state) {
  $t_nid = $form['field_eval_internship']['und']['#default_value'][0];
  $form['field_eval_student']['und']['#options'] = array();
  
  if ($t_nid) {
    $t_int_node = node_load($t_nid);
    if (($t_int_node) && (!empty($t_int_node->field_int_assignment['und']))) {
     // build the drop down for the students assigned to this internship
     foreach ($t_int_node->field_int_assignment['und'] as $t_assn) {
       if (!empty($t_assn['target_id'])) {
         $student_profile = profile2_load($t_assn['target_id']); 
         if (!empty($student_profile)) {
           $form['field_eval_student']['und']['#options'][$t_assn['target_id']] = $student_profile->field_stp_fname['und'][0]['value'] . " ";
           $form['field_eval_student']['und']['#options'][$t_assn['target_id']] .= $student_profile->field_stp_lname['und'][0]['value'];
         }
       }
       
     }
     // set the default title to pass validation; it will be amended in ims_evaluation_node_submit
     $form['title']['#default_value'] = 'MSE: '. $t_int_node->title . '--';
     // set default supervisor name
     $form['field_eval_supervisor_name']['und'][0]['value']['#default_value'] = $t_int_node->field_int_sup_name['und'][0]['value'];
    }
    // need an extra submit function to set the title
    $form['#submit'][] = 'ims_evaluation_node_submit';
  }
  else {
    watchdog('Mid-semester evaluation', 'Illegal internship node ID: %nid', $t_nid);
  }
  
 }
/**
* @file
* Build the drop-down list of students from the internship node
* Set the default supervisor name to the supervisor on the internship
* 
*/
/* Implements hook_form_FORM_ID_alter(). */
 function ims_form_final_evaluation_node_form_alter(&$form, &$form_state) {
  $t_nid = $form['field_fin_internship']['und']['#default_value'][0];
  $form['field_fin_student']['und']['#options'] = array();
  
  if ($t_nid) {
    $t_int_node = node_load($t_nid);
    if (($t_int_node) && (!empty($t_int_node->field_int_assignment['und']))) {
     // build the drop down for the students assigned to this internship
     foreach ($t_int_node->field_int_assignment['und'] as $t_assn) {
       if (!empty($t_assn['target_id'])) {
         $student_profile = profile2_load($t_assn['target_id']); 
         if (!empty($student_profile)) {
           $form['field_fin_student']['und']['#options'][$t_assn['target_id']] = $student_profile->field_stp_fname['und'][0]['value'] . " ";
           $form['field_fin_student']['und']['#options'][$t_assn['target_id']] .= $student_profile->field_stp_lname['und'][0]['value'];
         }
       }
       
     }
     // set the default title to pass validation; it will be amended in ims_evaluation_node_submit
     $form['title']['#default_value'] = 'FE: '. $t_int_node->title . '--';
     // set default supervisor name (shares field name with Evaluation content type)
     $form['field_eval_supervisor_name']['und'][0]['value']['#default_value'] = $t_int_node->field_int_sup_name['und'][0]['value'];
    }
    // need an extra submit function to set the title
    $form['#submit'][] = 'ims_final_evaluation_node_submit';
  }
  else {
    watchdog('Final evaluation', 'Illegal internship node ID: %nid', $t_nid);
  }
  
 }
/**
* @file
* If logged in user is a student, then set defaults to some fields in the choice node.
* Set the title and set the semester to the active semester
*/
/* Implements hook_form_FORM_ID_alter(). */
 function ims_form_internship_choice_node_form_alter(&$form, &$form_state) {
  global $user;
  
  $course_match = 0;
  //clear course match from previous sessions
  variable_set('course_match', $course_match);
      
  $t_role = "student";
  $form['#validate'][] = 'ims_internship_choice_validation';
  $form['#submit'][] = 'ims_internship_choice_node_submit';
  
  // only set default values for students and when she is creating a new choice (nid not set)
  if (in_array($t_role, $user->roles) && $form['nid']['#value'] == NULL) {
    // get the student profile
    $profile_values = profile2_load_by_user($user->uid);
    
    if (!empty($profile_values)) {

      $std_profile = $profile_values['student_profile'];

      // get the internship node
      $t_node = $form['#node'];
      $nid = $t_node->field_ch_internship['und'][0]['target_id'];
      $int_node = node_load($nid);
      if (isset($int_node)) {
        $int_course = $int_node->field_int_course['und'][0]['target_id'];
        $course_match++;
      }
      
      // get the datatel student record
      $nid = $std_profile->field_stp_datatel_student['und'][0]['target_id'];       
      $node = node_load($nid);
      if (isset($node)) {
        $std_course = $node->field_st_course['und'][0]['tid'];    
        $course_match++;
      } 
    
      if (($course_match == 2) && ($int_course == $std_course)) $course_match++;
      
      //save course match for validation
      variable_set('course_match', $course_match);
      
      $dTitle = (string) $int_node->title;
      $dTitle .= '-';
      $dTitle .= (string) $std_profile->field_stp_fname['und'][0]['value'];
      $dTitle .= ' ';
      $dTitle .= (string) $std_profile->field_stp_lname['und'][0]['value'];
      $dTitle .= ' (';
      $dTitle .= (string) $user->name;
      $dTitle .= ')';
      
      $form['title']['#default_value'] = $dTitle;         
      $form['field_ch_student']['und']['#default_value'] = array($std_profile->pid);
    }
  }
}
/**
* @file
* If logged in user is a supervisor, then set defaults to some fields in the internship node.
* Also if supervisor, set the semester to the active semester
*/
/* Implements hook_form_FORM_ID_alter(). */
 function ims_form_internship_node_form_alter(&$form, &$form_state) {
  global $user;
  // default title size is 60, which is too wide for the left panel of a two panel form
  $form['title']['#size'] = 53;
  
  $t_role = "supervisor";

  // only set default values for supervisors and when she is creating a new internship (nid not set)
  if (in_array($t_role, $user->roles) && $form['nid']['#value'] == NULL) {
    // get the supervisor profile
    $profile_values = profile2_load_by_user($user->uid);
    
    if (!empty($profile_values)) {
      // get the active semester
      $tid = ims_get_active_semester();
      if (isset($tid)){
          $form['field_int_semester']['und']['#default_value'] = array($tid);   
      }
      $super_profile = $profile_values['supervisor'];
      
      $form['field_int_org_id']['und']['#default_value'] = array($super_profile->field_sup_org['und'][0]['target_id']);     
      $form['field_int_sup_name']['und'][0]['value']['#default_value'] = $super_profile->field_sup_name['und'][0]['value'];
      $form['field_int_sup_phone']['und'][0]['value']['#default_value'] = $super_profile->field_sup_phone['und'][0]['value'];
      $form['field_int_sup_email']['und'][0]['email']['#default_value'] = $super_profile->field_sup_email['und'][0]['email'];
    }
  }
  else {
    // build the student profile list for the assignment drop-down
    $form['field_int_assignment']['und']['#options'] = array();
    $form['field_int_assignment']['und']['#options']['_none'] = "- None -";
    
    $course_tid = $form['field_int_course']['und']['#default_value'][0];
    
    if ($course_tid != NULL) {
      //the internship is for a course; find only those students who are registered for the course
      // execute the Students Course view. It will return all the students taking a particular course
      // pass in the course TID as an
      $view_name = "students_in_a_course";
      $display_id = "block";  
      $results = views_get_view_result($view_name, $display_id,  $course_tid);
      // $results should be a list students taking the course for which this internship is assigned
      foreach ($results as $result) {
        
        if ((empty($result->field_field_stp_assignment)) || 
            ($result->field_field_stp_assignment[0]['raw']['target_id'] == $form['nid']['#value'])) {       
          $form['field_int_assignment']['und']['#options'][$result->pid] = $result->field_field_stp_fname[0]['raw']['value'] . " ";
          $form['field_int_assignment']['und']['#options'][$result->pid] .= $result->field_field_stp_lname[0]['raw']['value'];
        }  
      }  
    }
    // this adds your custom validation function to the form validation array
    $form['#validate'][] = 'ims_internship_node_validation';

    // additional submit function for adding profile2
    $form['#submit'][] = 'ims_internship_node_submit';
  }
}
/**
* @file
* Change the input size of the title to 45.
* Implements hook_form_FORM_ID_alter().
**/
 function ims_form_organization_node_form_alter(&$form, &$form_state) {
    $form['title']['#size'] = 45;
 }
 /**
* @file ims_form_profile2_edit_supervisor
* @param $form
* @param $form_state
* For supervisors: truncate the list of orgs available to choose from; allow them to change just once
* For admins: add submit function to add edit permission on the org node for this supervisor
* For all: modify the drop down display to include the repository
* 
* Implements hook_form_profile2_edit_PROFILE_TYPE_form_alter
**/
 function ims_form_profile2_edit_supervisor_form_alter(&$form, &$form_state) {
  global $user;

  // supervisors cannot change their org, therefore we'll truncate the list
  // administrators and archive admins can change a supervisor to any org.
  if (in_array("supervisor", $user->roles)) {
    // truncate the dropdown.
    $form['profile_supervisor']['field_sup_org']['und']['#options'] = array();
    
    $multi_org = $form['profile_supervisor']['field_sup_multi_org']['und'][0]['value']['#default_value'];
    
    //if multi_org flag is 0 then supervisor (or admin) has previously verified her org. No further changes are allowed.
    if ($multi_org == 0) {
      // the supervisor profile will have a #default_value because it was populated during registration
      // @see ims_user_submit
      $nid = $form['profile_supervisor']['field_sup_org']['und']['#default_value'][0];
      // load the organization node to get the title
      $node = node_load($nid);
    
      // testing $node as a precaution; should *always* be populated
      if (isset($node)) {
        $org_title = trim(substr($node->title, 0, 45));
        if (!empty($node->field_org_repository)) {
          $org_title .= " - " . trim(substr($node->field_org_repository['und'][0]['value'], 0, 30));
        }

       $form['profile_supervisor']['field_sup_org']['und']['#options'][$nid] = $org_title;
      }
    }
    else {     
     // $multi_org is 1 if there was more than one choice for org when the supervisor registered
     // otherwise it's set to the org nid; we don't use it as the nid but it saves us from having to find the org again...
     // since we found an exact match during the registration process 
     if ($multi_org > 1) {
        // the supervisor profile will have a #default_value because it was populated during registration
        // @see ims_user_submit
        $nid = $form['profile_supervisor']['field_sup_org']['und']['#default_value'][0];
        // load the organization node to get the title
        $node = node_load($nid);    
        // testing $node as a precaution; should *always* be populated
        if (isset($node)) {
          $org_title = trim(substr($node->title, 0, 45));
          if (!empty($node->field_org_repository)) {
            $org_title .= " - " . trim(substr($node->field_org_repository['und'][0]['value'], 0, 30));
          }
          $form['profile_supervisor']['field_sup_org']['und']['#options'][$nid] = $org_title;
        }
      }    
      else {
        // when this supervisor registered there were multiple matches on the email domain (e.g. harvard.edu)
        // build a list of all orgs with this supervisors email domain
        // the supervisor can then pick the correct organization, we'll update the acl for that org, and...
        // set the multi org flag to 0. 
        
        $domain = ims_get_domain($form['profile_supervisor']['field_sup_email']['und'][0]['email']['#default_value']); 
        $entity_type = "node"; 
        $bundle = "organization";     
        $field_name = "field_org_email";
        $value = $domain;
      
        $oids = tedbow_utils_find_entities_with_field_value($entity_type, $bundle, $field_name, $value, $column = 'value', $access = '1');
        if (!empty($oids)) {
          foreach($oids as $nid) {
            $node = node_load($nid);
            $org_title = trim(substr($node->title, 0, 45));
            if (!empty($node->field_org_repository)) {
              $org_title .= " - " . trim(substr($node->field_org_repository['und'][0]['value'], 0, 30));
            }
 
            $form['profile_supervisor']['field_sup_org']['und']['#options'][$nid] = $org_title;
          }
        }
      }
      // set multi_org to 0; supervisor gets one chance to verify or pick the correct org
      $form['profile_supervisor']['field_sup_multi_org']['und'][0]['value']['#default_value'] = 0;
      // add our custom submit function to the top of the list
      // we want our submit function executed first before profile2_submit_handler resets $form_state['values']
      // this submit function will create an acl for the org linked to this supervisor. This gives the supervisor
      // edit permission on her org, but only her org
      $submit_functions = $form['#submit'];
      array_unshift($submit_functions, 'ims_super_profile2_submit');
      $form['#submit'] = $submit_functions;
    }
  }
  else {
   // rebuild the organization drop down to include the repository
   $options = $form['profile_supervisor']['field_sup_org']['und']['#options'];
   foreach ($options as $nid => $title) {
     if ($nid == "_none") {
      continue;
     }
     $node = node_load($nid);
     if (isset($node)) {     
       if (strlen($node->field_org_repository['und'][0]['value']) > 0) {
         $org_title = trim(substr($node->title, 0, 45));  
         $org_title .= " - " . trim(substr($node->field_org_repository['und'][0]['value'], 0, 30));
         $form['profile_supervisor']['field_sup_org']['und']['#options'][$nid] = $org_title;
       }     
     }
   }
   // set multi_org to 0; supervisor will not be allowed to change the org after an admin has set it
   $form['profile_supervisor']['field_sup_multi_org']['und'][0]['value']['#default_value'] = 0;
   // add our custom submit function to the top of the list
   // we want our submit function executed first before profile2_submit_handler resets $form_state['values']
   $submit_functions = $form['#submit'];
   array_unshift($submit_functions, 'ims_super_profile2_submit');
   $form['#submit'] = $submit_functions;
  } 
 } 
  /**
* @file
* The assignment cannot be changed on the student profile
*
* Implements hook_form_profile2_edit_PROFILE_TYPE_form_alter
**/
 function ims_form_profile2_edit_student_profile_form_alter(&$form, &$form_state) {
  // truncate the dropdown.
  $form['profile_student_profile']['field_stp_assignment']['und']['#options'] = array();

  // test to see if the student has an assignment, if no just stuff '- None -' into the drop down.
  if (!empty($form['profile_student_profile']['field_stp_assignment']['und']['#default_value'])) {
    $nid = $form['profile_student_profile']['field_stp_assignment']['und']['#default_value'][0];
    // load the internship node to get the title
    $node = node_load($nid);
    
    // testing $node as a precaution; should *always* be populated
    if (isset($node)) {
      $title = "";
      $ref_title = $node->title;
      // get org title
      $org_nid = $node->field_int_org_id['und'][0]['target_id'];
      $node = node_load($org_nid);
      if (isset($node)) {
        $title = $node->title . " - ";
      }
      $title .= $ref_title;
      $form['profile_student_profile']['field_stp_assignment']['und']['#options'][$nid] = $title;
      
    }
  }
  else {
   $form['profile_student_profile']['field_stp_assignment']['und']['#options']['_none'] = '- None -';
  }  
 } 
/**
* @file
* Specifies rules for restricting student user registration based on email addr found in datatel student table
* If not a simmons.edu domain, assume supervisor.  Check domain in Org table.
*/
/**
* Implements hook_form_FORM_ID_alter().
**/
 function ims_form_user_register_form_alter(&$form, &$form_state) {
  global $user;

  variable_set('ims_assigned_role', array());
  
  $t_role = "administrator";
  
  // allow administrator to circumvent extra validation but only on the test server.
  if (!in_array($t_role, $user->roles) || ($GLOBALS['_SERVER']['HTTP_HOST'] == '127.0.0.1')) {
    // this adds your custom validation function to the form validation array
    $form['#validate'][] = 'ims_user_register_validation';
    // additional submit function for adding profile2
    $form['#submit'][] = 'ims_user_submit';
  } 
 }
  /*
  * Return the active semester
  */
 function ims_get_active_semester() {
   $tid = NULL;
   
   //get vocabulary ID for "Semesters" vocabulary
   // we only want the active semester
   $vid = taxonomy_vocabulary_machine_name_load("semesters")->vid;

   //get all the terms in the vocabulary. there should only be a few
   $terms = taxonomy_get_tree($vid, $parent = 0, $max_depth = NULL, $load_entities = TRUE);
      
   foreach ($terms as $term) {
     // find the active semester
     if ($term->field_tax_sem_active['und'][0]['value'] == '1') {
       $tid = $term->tid;
       break;
     }
   }
   return $tid;
 }
/*
 * Extract the domain from an email address
 * ims_get_domain
 * @param string $email
 * @return string $domain
 */
 function ims_get_domain($email) {
  
  $splitIndex = strpos($email, '@')+1;
  $emailLength = strlen($email);
  $domain = substr($email, $splitIndex, $emailLength);
  
  return $domain;
 }
 function ims_internship_choice_node_submit(&$form, &$form_state) { 
  // load internship node, increment chosen and save it
  // need to test for new choice, deleted choice (decrement chosen) or changed choice (inc and dec)
  $t_internship_id = $form_state['values']['field_ch_internship']['und'][0]['target_id'];
  
  if ($form['nid']['#value'] == NULL) {
    //new choice. get chosen and increment   
    $t_int_node = node_load($t_internship_id);
    if (isset($t_int_node)) {
      $t_chosen = $t_int_node->field_int_chosen['und'][0]['value'];
      $t_chosen++;
      $t_int_node->field_int_chosen['und'][0]['value'] = $t_chosen;
      
      node_save($t_int_node);
    }
  }
 
  // execute the Student Choices view. it will return all of the choices a student has made so far
  // the view uses the logged in user's uid as context
  $view_name = "student_choices";
  $display_id = "block";  
  $results = views_get_view_result($view_name, $display_id);
  //grab the rank the student just entered
  $t_rank = $form_state['values']['field_ch_rank']['und'][0]['value'];
  foreach ($results as $result) {
    // if the student is changing the current rank to a rank she has chosen before but for a different internship
    // then give that internship the old rank from this internship
    if (($t_internship_id != $result->node_field_data_field_ch_internship_nid) && 
       ($t_rank == $result->field_field_ch_rank[0]['raw']['value'])) {
        $t_ch_nid = $result->field_ch_student_profile_nid;
        $t_ch_node = node_load($t_ch_nid); // load the choice node
        $arg0 = $form_state['build_info']['args'][0];
        $t_ch_node->field_ch_rank['und'][0]['value'] = $arg0->field_ch_rank['und'][0]['value'];
        node_save($t_ch_node);
    }
  }
 }

 function ims_internship_choice_validation(&$form, &$form_state) { 
  //grab the rank the student had just entered
  $t_rank = $form_state['values']['field_ch_rank']['und'][0]['value'];
  //grab the nid of the internship the student is attempting to choose
  $t_internship_id = $form_state['values']['field_ch_internship']['und'][0]['target_id'];
  
  // execute the Student Choices view. it will return all of the choices a student has made so far
  // the view uses the logged in user's uid as context
  $view_name = "student_choices";
  $display_id = "block";
  $results = views_get_view_result($view_name, $display_id);
  
  // we only need to validate on add.
  if ($form['nid']['#value'] == NULL) {
    //check to see how many choices this student has already made
    if (count($results) > 2){
     form_set_error('student choice', t('You have already made three choices.'));
    }
    
    $course_match = variable_get('course_match');
    if ($course_match < 3) {
      form_set_error('student choice', t('You may only choose internships for a course in which you are enrolled.'));
    }
    // if the student has choices already, make sure she doesn't pick the same internship twice or use the same rank
    if (count($results) > 0) {
      foreach ($results as $result){
        if ($t_internship_id == $result->node_field_data_field_ch_internship_nid) {
          form_set_error('student choice', t('You already have chosen this internship.'));
          break;
        }
       if ($t_rank == $result->field_ch_student_profile__field_data_field_ch_rank_field_ch_) {
          form_set_error('student choice', t('You have already used rank ' . $t_rank));
          break;
        }
      }
    }
  }
 
 }
 function ims_internship_node_submit(&$form, &$form_state) {
   //unassign previously assigned students and then assign new ones
   //$t_pre holds the list of students previously assigned; it may be empty
   $t_args0 = $form_state['build_info']['args'][0];
   $t_pre = $t_args0->field_int_assignment['und'];
   
   //$t_new holds the list of newly assigned students; it may be empty
   $t_new = $form_state['values']['field_int_assignment']['und'];
   
   if (!(empty($t_pre))) {
     ims_unassign_students($t_pre);
   }
    
    $t_assn = array();
    //assign new students
    foreach ($t_new as $t_assn) {
      $t_pid = (int) $t_assn['target_id'];
      
      if ($t_pid > 0) {
        $student_profile = profile2_load($t_pid);
        //make sure we have a valid student profile object
        if (!(empty($student_profile))) {
          $student_profile->field_stp_assignment['und'][0]['target_id'] = $form_state['values']['nid'];
          profile2_save($student_profile);
        }
      }     
    }
 }
 function ims_internship_node_validation(&$form, &$form_state) {
  $t_count = count($form_state['values']['field_int_assignment']['und']);
  if ($t_count > (int) $form_state['values']['field_int_positions']['und'][0]['value']) {
    form_set_error('mail', t('The number of students assigned may not exceed the number of positions available.'));
  }
 }
/**
* @file
* Extra deletion logic after deleting a node.
*/
/* Implements hook_node_delete(). */
 function ims_node_delete($node) {
  
  switch ($node->type) {
    case ('internship_choice'):
      //we're deleting an internship choice, so we've got to load the internship and decrement chosen
     $t_internship_id = $node->field_ch_internship['und'][0]['target_id'];
      $t_int_node = node_load($t_internship_id);
      //do we have a valid node?
      if (isset($t_int_node)) {
        $t_chosen = $t_int_node->field_int_chosen['und'][0]['value'];
        if ($t_chosen > 0) {
           $t_chosen--;
           $t_int_node->field_int_chosen['und'][0]['value'] = $t_chosen;
      
           node_save($t_int_node);
        }
      }
      break;
    case ('internship'):
      //we're deleting an internship. unassign all students assigned to this internship
      $t_assignments = $node->field_int_assignment['und'];
      
      if (!(empty($t_assignments))) {
        ims_unassign_students($t_assignments);
      }
      
      break;
    default:
      break;
  }
 }
 /*
  * Extra submit function for profile2 supervisor
  * @function ims_super_profile2_submit
  * this will be called one time for supervisors allowing them to verify their org
  * it will be called every time an admin edits and saves a supervisor's profile
  * This function gives the supervisor edit permission on her affiliated organization
  * @param $form
  * @param $form_state
  */
function ims_super_profile2_submit(&$form, &$form_state) {
  
  $super_profile = $form_state['profile2'];
  $uid = $super_profile->uid;
  $user = user_load($uid);
  
  // if the logged in user can edit any supervisor's profile then the user can move the supervisor to another org.
  // we must delete the acl edit permission from the old org node before adding it to the new.
  if (user_access('edit any supervisor profile')) {
    //get the old org nid
    $nid = $super_profile->field_sup_org['und'][0]['target_id'];
   
    // get the acl_id associated with update access to this nid
    $acl_id = db_query("SELECT acl_id FROM {acl_node} WHERE nid = :nid AND grant_update = 1", array(
    'nid' => $nid,
     ))->fetchField();
     
    // it's possible no update permission was ever granted
    if (isset($acl_id)) {
      //delete acl_id/uid combo from acl_user
      acl_remove_user($acl_id, $uid);
    }
  }
 
  // now add update permission on the new node
  $nid = $form_state['values']['profile_supervisor']['field_sup_org']['und'][0]['target_id'];
  
  // the acl routines need the username in $form_state 
  $form_state['values']['name'] = $user->name;
  
  // give update permission to this supervisor for this organization
  ims_add_org_acl($uid, $form_state, $nid); 
}
/**
* @file
* unassign previously assigned students
*/
 function ims_unassign_students($assignments) {
   foreach ($assignments as $t_assn) {
     $t_pid = (int) $t_assn['target_id'];
      
     if ($t_pid > 0) {
       $student_profile = profile2_load($t_pid);
       //make sure we have a valid student profile object
       if (!(empty($student_profile))) {
          $student_profile->field_stp_assignment = array();
          profile2_save($student_profile);
       }
     }
   }
 }
/**
 * Implements hook_user_presave().
 */
function ims_user_presave(&$edit, $account, $category) {
  // only assign role of student or supervisor on new accounts
  if (isset($account->is_new) && !empty($account->is_new)) {
    $user_roles = user_roles(TRUE);
    $roles_to_add = array();

    // Make sure the roles key exists.
    if (!isset($edit['roles'])) {
      $edit['roles'] = array();
    }

    $t_role = array_filter(variable_get('ims_assigned_role', array()));
    if (!empty($t_role)) {
      $roles_to_add = array_intersect($user_roles, $t_role); 

      // Add in the new roles to override the current roles.
      $edit['roles'] = $roles_to_add + $edit['roles'];
    }
  }
}

function ims_user_register_validation(&$form, &$form_state) {

  // look into making the literal a constant and have all constants in a .inc 
  $schoolDomains = 'simmons.edu';

  //clear out assigned role for next user
  variable_set('ims_assigned_role', array());
  
  $email = $form_state['values']['mail'];
  $domain = ims_get_domain($email);

  $entity_type = "node";

  if (($domain == $schoolDomains) ) {
    // we've got a Simmons student (Simmons supervisors need not register)
   
    $bundle = "student";
    $field_name = "field_st_email";  // this is not a field of type email as it is with supervisors, hence $column is 'value'
    $value = $email;
        
    $oid = tedbow_utils_find_entity_with_field_value($entity_type, $bundle, $field_name, $value, $column = 'value', $access = '1'); 
    if (!empty($oid)) {      
      //set ims_assigned_role to student; used by ims_user_presave
      //also store object ID of Student; used by ims_user_submit
      variable_set('ims_assigned_role', array('student', $oid));
    }
    else {
       form_set_error('mail', t('Sorry but you don\'t appear to be registered for an internship course this semester. Send email to archives_education@simmons.edu if you have questions.'));
    }
  }
  else {
   // we've got a potential supervisor, check org table for email 1, email 2, or domain match
   // if none match, then the user may not register
    $bundle = "organization";
    $field_name = "field_org_email_1";
    $value = $email;
    
    // look for a match on primary email address first
    // returns org id (nid of node of content type organization)
    $oid = tedbow_utils_find_entity_with_field_value($entity_type, $bundle, $field_name, $value, $column = 'email', $access = '1');
    if (!empty($oid)) {
      //set ims_assigned_role to supervisor; used by ims_user_presave
      variable_set('ims_assigned_role', array('supervisor', $oid));
      variable_set('ims_multi_org', $oid);
    }
    else {
      $field_name = "field_org_email_2";
      
      // second, check for a match on secondary email
      // returns org id (nid of node of content type organization)
      $oid = tedbow_utils_find_entity_with_field_value($entity_type, $bundle, $field_name, $value, $column = 'email', $access = '1');
      if (!empty($oid)) {
        //set ims_assigned_role to supervisor; used by ims_user_presave
        variable_set('ims_assigned_role', array('supervisor', $oid));
        variable_set('ims_multi_org', $oid);
      }
      else {
         $field_name = "field_org_email";
         $value = $domain;
         // third , check for a match on the email domain
         // returns org id (nid of node of content type organization)
         // if there is more than one org with the same email domain (e.g., harvard.edu), only the first will be returned
         $oids = tedbow_utils_find_entities_with_field_value($entity_type, $bundle, $field_name, $value, $column = 'value', $access = '1');
         if (!empty($oids)) {
           //set ims_assigned_role to supervisor; used by ims_user_presave
           //save object id for later use as well
           variable_set('ims_assigned_role', array('supervisor', $oids[0]));
           
           //if multiple OIDs were returned, we need to set the multi_org flag in the supervisor profile
           //when the supervisor logs in she can refine the org to the correct one.
           
           if (count($oids) == 1) {
             $mult_org = $oids[0];
           }
           else {
             $multi_org = 1;            
           }
           variable_set('ims_multi_org', $multi_org);
         }
         else {
           form_set_error('mail', t('Sorry but we cannot register you with that email address. Send email to archives_education@simmons.edu if you have questions.'));
         }
      }
    }
  }
}
/**
 * additional submit function for adding a profile2 profile
 */
function ims_user_submit($form, &$form_state) {
  $t_role = array();
  $t_role = variable_get('ims_assigned_role', array());
  
  //multi_org is either the nid of the organization or 1 if there were multiple orgs with the same domain.
  $multi_org = variable_get('ims_multi_org', 1);
  
  if ($t_role[0] == 'supervisor') {
    $uid = $form_state['values']['uid'];
    // create profile object
    $profile = profile_create(array('user' => $uid, 'type' => 'supervisor'));

    // assign organization ID, store in $t_role[1] at validation time
    $profile->field_sup_org['und'][0]['target_id'] = $t_role[1]; //stored by variable_set in validation
    // assign multi_org flag
    $profile->field_sup_multi_org['und'][0]['value'] = $multi_org;
    // assign email address
    $profile->field_sup_email['und'][0]['email'] = (string) $form_state['values']['mail']; 

    // save profile
    profile2_save($profile);
    $uid = $form_state['values']['uid'];
  }
  elseif ($t_role[0] == 'student') {
   $oid = $t_role[1]; // stored in ims_user_register_validation
   $node = node_load($oid);
   if (isset($node)) {
     $uid = $form_state['values']['uid'];
     
     // change datatel student 'record' owner (author) to the new student
     $node->uid = $uid;
     node_save($node);
     
     // create profile object
     $profile = profile_create(array('user' => $uid, 'type' => 'student_profile'));
     // assign student ID, stored in $t_role[1] at validation time
     $profile->field_stp_datatel_student['und'][0]['target_id'] = $t_role[1]; 
     // assign default first name
     $profile->field_stp_fname['und'][0]['value'] = (string) $node->field_st_fname['und'][0]['value'];
     // assign default last name
     $profile->field_stp_lname['und'][0]['value'] = (string) $node->field_st_lname['und'][0]['value'];

     // save profile
     profile2_save($profile);
   }
  }
}
/**
 * implements hook_views_api().
 */
function ims_views_api() {
  return array('api' => '3.0');
}
/**
 * Implements hook_views_default_views().
 */
function ims_views_default_views() {
  $path = './' . drupal_get_path('module', 'ims') . '/views/*.inc';
  $views = array();
  foreach (glob($path) as $views_filename) {
    require_once($views_filename);
  }
  return $views;
}
/**
 * Implements hook_views_query_alter().
 */
function ims_views_query_alter(&$view, &$query) {

  global $user;
 
  switch ($view->name) {
   case 'internships':
     $t_role = "student";

     // only alter the query for students
     if (in_array($t_role, $user->roles)) {
      // get the student profile
      $profile_values = profile2_load_by_user($user->uid);
    
      if (!empty($profile_values)) {  
        $student_profile = $profile_values['student_profile'];
        // get the datatel student record
        $nid = $student_profile->field_stp_datatel_student['und'][0]['target_id'];
        $node = node_load($nid);
        if (isset($node)) {
          // set the course condition in the view to the course in which the student is enrolled
          $query->where[1]['conditions'][2]['value'][0] = $node->field_st_course['und'][0]['tid'];    
        } 
      }
     }
     break;
   default:
     break;
  } 
}
/* Borrowed two functions from tedbow utils so I wouldn't have to enable the module
 * Thanks Ted!!
 * modified them to allow query to be run as user 1 (administrator)
 */
/**
 * Get entity ids having matching value in a field
 * @param string $entity_type
 * @param string$bundle
 * @param String $field_name
 * @param string $value
 * @param string $column
 * @param string $access
 *  if '1' then run query as user 1, i.e., administrator
 * @param array $entity_ids
 * 	Limit to only these entity ids
 * @return array
 */
function tedbow_utils_find_entities_with_field_value($entity_type, $bundle, $field_name, $value, $column, $access, $entity_ids = array()){
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type',$entity_type, '=');
  $query->entityCondition('bundle',$bundle, '=');
  $query->fieldCondition($field_name, $column, $value);
  if ($access == '1') {
    $query->addMetaData('account', user_load(1));
  }
  if(!empty($entity_ids)){
    $query->entityCondition('entity_id',$entity_ids, 'IN');
  }
  $result = $query->execute();
  return array_keys(isset($result[$entity_type])?$result[$entity_type]:array());
}
/**
* Get entity that has matching value in a field
* @param string $entity_type
* @param string$bundle
* @param String $field_name
* @param string $value
* @param string $column
* @param string $access
*   if '1' then run query as user 1
* @param array $entity_ids
* 	Limit to only these entity ids
* @return array
*/

function tedbow_utils_find_entity_with_field_value($entity_type, $bundle, $field_name, $value, $column, $access){
  $entities = tedbow_utils_find_entities_with_field_value($entity_type, $bundle, $field_name, $value, $column, $access);
  return array_shift($entities);
}